import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:meal_box/core/constants/app_colour.dart';
import 'package:meal_box/presentation/bloc/home/home_bloc.dart';
import 'package:meal_box/presentation/bloc/home/home_event.dart';
import 'package:meal_box/presentation/bloc/home/home_state.dart';
import 'package:meal_box/presentation/pages/homepage/widget/regionbubble.dart';
import 'package:meal_box/presentation/widgets/shimmer_widget.dart';

class RegionStrip extends StatelessWidget {
  final HomeState state;
  const RegionStrip({super.key, required this.state});

  // Emoji map for visual flair
  static const Map<String, String> _flags = {
    'Afghan': '🇦🇫',
    'Albanian': '🇦🇱',
    'Algerian': '🇩🇿',
    'Andorran': '🇦🇩',
    'Angolan': '🇦🇴',
    'Antiguan, Barbudan': '🇦🇬',
    'Argentine': '🇦🇷',
    'Armenian': '🇦🇲',
    'Aruban': '🇦🇼',
    'Australian': '🇦🇺',
    'Austrian': '🇦🇹',
    'Azerbaijani': '🇦🇿',
    'Bahamian': '🇧🇸',
    'Bahraini': '🇧🇭',
    'Bangladeshi': '🇧🇩',
    'Barbadian': '🇧🇧',
    'Belarusian': '🇧🇾',
    'Belgian': '🇧🇪',
    'Belizean': '🇧🇿',
    'Beninese': '🇧🇯',
    'Bermudian': '🇧🇲',
    'Bhutanese': '🇧🇹',
    'Bolivian': '🇧🇴',
    'Bosnian, Herzegovinian': '🇧🇦',
    'Motswana': '🇧🇼',
    'Brazilian': '🇧🇷',
    'Bruneian': '🇧🇳',
    'Bulgarian': '🇧🇬',
    'Burkinabe': '🇧🇫',
    'Burundian': '🇧🇮',
    'Cambodian': '🇰🇭',
    'Cameroonian': '🇨🇲',
    'Canadian': '🇨🇦',
    'Cape Verdian': '🇨🇻',
    'Caymanian': '🇰🇾',
    'Central African': '🇨🇫',
    'Chadian': '🇹🇩',
    'Chilean': '🇨🇱',
    'Chinese': '🇨🇳',
    'Colombian': '🇨🇴',
    'Costa Rican': '🇨🇷',
    'Croatian': '🇭🇷',
    'Cuban': '🇨🇺',
    'Cypriot': '🇨🇾',
    'Czech': '🇨🇿',
    'Danish': '🇩🇰',
    'Djibouti': '🇩🇯',
    'Dominican': '🇩🇴',
    'Congolese': '🇨🇩',
    'Ecuadorean': '🇪🇨',
    'Egyptian': '🇪🇬',
    'Salvadoran': '🇸🇻',
    'Equatorial Guinean': '🇬🇶',
    'Eritrean': '🇪🇷',
    'Estonian': '🇪🇪',
    'Ethiopian': '🇪🇹',
    'Faroese': '🇫🇴',
    'Fijian': '🇫🇯',
    'Finnish': '🇫🇮',
    'French': '🇫🇷',
    'Gabonese': '🇬🇦',
    'Gambian': '🇬🇲',
    'Georgian': '🇬🇪',
    'German': '🇩🇪',
    'Ghanaian': '🇬🇭',
    'Gibraltar': '🇬🇮',
    'Greek': '🇬🇷',
    'Greenlandic': '🇬🇱',
    'Grenadian': '🇬🇩',
    'Guadeloupian': '🇬🇵',
    'Guamanian': '🇬🇺',
    'Guatemalan': '🇬🇹',
    'Channel Islander': '🇬🇬',
    'Guinean': '🇬🇳',
    'Guinea-Bissauan': '🇬🇼',
    'Guyanese': '🇬🇾',
    'Haitian': '🇭🇹',
    'Honduran': '🇭🇳',
    'Hong Konger': '🇭🇰',
    'Hungarian': '🇭🇺',
    'Icelander': '🇮🇸',
    'Indian': '🇮🇳',
    'Indonesian': '🇮🇩',
    'Iranian': '🇮🇷',
    'Iraqi': '🇮🇶',
    'Irish': '🇮🇪',
    'Israeli': '🇮🇱',
    'Italian': '🇮🇹',
    'Ivorian': '🇨🇮',
    'Jamaican': '🇯🇲',
    'Japanese': '🇯🇵',
    'Jordanian': '🇯🇴',
    'Kazakhstani': '🇰🇿',
    'Kenyan': '🇰🇪',
    'Kosovar': '🇽🇰',
    'Kuwaiti': '🇰🇼',
    'Kirghiz': '🇰🇬',
    'Laotian': '🇱🇦',
    'Latvian': '🇱🇻',
    'Lebanese': '🇱🇧',
    'Mosotho': '🇱🇸',
    'Liberian': '🇱🇷',
    'Libyan': '🇱🇾',
    'Liechtensteiner': '🇱🇮',
    'Lithuanian': '🇱🇹',
    'Luxembourger': '🇱🇺',
    'Malagasy': '🇲🇬',
    'Malawian': '🇲🇼',
    'Malaysian': '🇲🇾',
    'Maldivan': '🇲🇻',
    'Malian': '🇲🇱',
    'Maltese': '🇲🇹',
    'Mauritian': '🇲🇺',
    'Mexican': '🇲🇽',
    'Moldovan': '🇲🇩',
    'Mongolian': '🇲🇳',
    'Montenegrin': '🇲🇪',
    'Moroccan': '🇲🇦',
    'Mozambican': '🇲🇿',
    'Burmese': '🇲🇲',
    'Namibian': '🇳🇦',
    'Nepalese': '🇳🇵',
    'Dutch': '🇳🇱',
    'New Zealander': '🇳🇿',
    'Nicaraguan': '🇳🇮',
    'Nigerien': '🇳🇪',
    'Nigerian': '🇳🇬',
    'North Korean': '🇰🇵',
    'Macedonian': '🇲🇰',
    'Norwegian': '🇳🇴',
    'Omani': '🇴🇲',
    'Pakistani': '🇵🇰',
    'Palestinian': '🇵🇸',
    'Panamanian': '🇵🇦',
    'Papua New Guinean': '🇵🇬',
    'Paraguayan': '🇵🇾',
    'Peruvian': '🇵🇪',
    'Filipino': '🇵🇭',
    'Polish': '🇵🇱',
    'Portuguese': '🇵🇹',
    'Puerto Rican': '🇵🇷',
    'Qatari': '🇶🇦',
    'Romanian': '🇷🇴',
    'Russian': '🇷🇺',
    'Rwandan': '🇷🇼',
    'Saint Lucian': '🇱🇨',
    'Samoan': '🇼🇸',
    'Sammarinese': '🇸🇲',
    'Saudi Arabian': '🇸🇦',
    'Senegalese': '🇸🇳',
    'Serbian': '🇷🇸',
    'Seychellois': '🇸🇨',
    'Sierra Leonean': '🇸🇱',
    'Singaporean': '🇸🇬',
    'Slovak': '🇸🇰',
    'Slovene': '🇸🇮',
    'Solomon Islander': '🇸🇧',
    'Somali': '🇸🇴',
    'South African': '🇿🇦',
    'South Korean': '🇰🇷',
    'South Sudanese': '🇸🇸',
    'Spanish': '🇪🇸',
    'Sri Lankan': '🇱🇰',
    'Sudanese': '🇸🇩',
    'Surinamer': '🇸🇷',
    'Swedish': '🇸🇪',
    'Swiss': '🇨🇭',
    'Syrian': '🇸🇾',
    'Taiwanese': '🇹🇼',
    'Tadzhik': '🇹🇯',
    'Tanzanian': '🇹🇿',
    'Thai': '🇹🇭',
    'Togolese': '🇹🇬',
    'Tongan': '🇹🇴',
    'Trinidadian': '🇹🇹',
    'Tunisian': '🇹🇳',
    'Turkish': '🇹🇷',
    'Turkmen': '🇹🇲',
    'Tuvaluan': '🇹🇻',
    'Ugandan': '🇺🇬',
    'Ukrainian': '🇺🇦',
    'Emirati': '🇦🇪',
    'British': '🇬🇧',
    'American': '🇺🇸',
    'Uruguayan': '🇺🇾',
    'Uzbekistani': '🇺🇿',
    'Ni-Vanuatu': '🇻🇺',
    'Venezuelan': '🇻🇪',
    'Vietnamese': '🇻🇳',
    'Yemeni': '🇾🇪',
    'Zambian': '🇿🇲',
    'Zimbabwean': '🇿🇼',
  };
  @override
  Widget build(BuildContext context) {
    final isLoading = state.isLoadingAreas;
    // Put local cuisine first if available
    final areas = _sortedAreas(state.areas, state.localCuisine);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Padding(
          padding: EdgeInsets.fromLTRB(16, 16, 16, 10),
          child: Text(
            '🌍 Explore by Region',
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: AppColors.textPrimary,
            ),
          ),
        ),
        SizedBox(
          height: 86,
          child: isLoading
              ? ListView.separated(
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  scrollDirection: Axis.horizontal,
                  itemCount: 6,
                  separatorBuilder: (_, __) => const SizedBox(width: 10),
                  itemBuilder: (_, __) => const Column(
                    children: [
                      ShimmerBox(width: 56, height: 56, borderRadius: 28),
                      SizedBox(height: 4),
                      ShimmerBox(width: 44, height: 10),
                    ],
                  ),
                )
              : ListView.builder(
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  scrollDirection: Axis.horizontal,
                  itemCount: areas.length,
                  itemBuilder: (context, i) {
                    final area = areas[i];
                    final isSelected =
                        state.selectedCategory == area &&
                        state.activeFilterTab == FilterTab.regions;
                    final flag = _flags[area] ?? '🍴';
                    return RegionBubble(
                      flag: flag,
                      label: area,
                      isSelected: isSelected,
                      isLocal: area == state.localCuisine,
                      onTap: () =>
                          context.read<HomeBloc>().add(HomeAreaSelected(area)),
                    );
                  },
                ),
        ),
        const SizedBox(height: 4),
      ],
    );
  }

  List<String> _sortedAreas(List<String> areas, String? local) {
    if (local == null || !areas.contains(local)) return areas;
    return [local, ...areas.where((a) => a != local)];
  }
}
